TTP_PROTOCOL = 253
DEFAULT_WINDOW_SIZE = 65535
MAX_PACKET_SIZE = 65535
HEADER_FORMAT = "!HHIIBBHHHI"
HEADER_FORMAT_IPV4 = "!BBHHHBBH4s4s"
SERVER_PORT = 8443
_SHARED_LOGGER = None
_SHARED_LOG_FILE_PATH = None